import image_0 from '../../assets/films/Conan.jpg';
import image_1 from '../../assets/films/Jujutsu Kaisen.jpg';
import image_2 from '../../assets/films/Haikyuu.jpg';
import image_3 from '../../assets/films/HMC.jpg';
import image_4 from '../../assets/films/Fairy Tail.jpg';
import image_5 from '../../assets/films/Naruto.jpg';
import image_6 from '../../assets/films/SA.jpg';
import image_7 from '../../assets/films/BSD.jpg';
import image_8 from '../../assets/films/TGDQ.jpg';
import image_9 from '../../assets/films/CSM.jpg';



const data = [
    {
        id: 0,
        name: "Conan Movie 26: Tàu Ngầm Sắt Màu Đen",
        desc: "Một thử nghiệm về một “công nghệ mới” nhất định dựa trên hệ thống nhận dạng khuôn mặt đang được tiến hành ở đó. Trong khi đó, Conan và Đội thám tử nhí đến thăm Hachijo-jima theo lời mời của Sonoko và nhận được một cuộc điện thoại từ Subaru Okiya thông báo rằng một nhân viên Europol đã bị sát hại ở Đức bởi Jin của Tổ chức Áo đen. Conan lo lắng, lẻn vào cơ sở và phát hiện ra rằng một nữ kỹ sư đã bị Tổ chức Áo đen bắt cóc…! Hơn nữa, một ổ USB chứa một số thông tin nhất định mà cô ấy sở hữu lại lọt vào tay tổ chức… Một bóng đen cũng len lỏi vào Ai Haibara..",
        image: image_0,
        logo: "",
        year: "2023",
        time: "1h49p",
        limit: "13+",
        actor: "Minami Takayam, Megumi Hayashibara, Wakana Yamazaki, Shuichi Ikeda, Kazujiko Inoue, YukitoshiHori,..",
        genre: "Movie",
        country: "Nhật Bản",
        video: "https://www.youtube.com/embed/NwnQI9izPFc",
    },
    {
        id: 1,
        name: "Jujutsu Kaisen",
        desc: "Chuyện kể về nam sinh trung học tên là Yuuji Itadori, cậu mang năng lực thể chất phi thường. Tuy nhiên cậu ấy lại muốn dành thời gian của mình trong Câu lạc bộ Tâm Linh. Một ngày sau cái chết của ông mình, cậu gặp Megumi Fushiguro, người đang tìm kiếm vật thể bị nguyền mà các thành viên câu lạc bộ của cậu tìm thấy. Đối mặt với những chú linh, Yuuji đã nuốt vật thể bị phong ấn để có được sức mạnh và cứu bạn bè của mình. vật thể cậu nuốt lại có mối nguy hiểm đến đáng sợ và từ đó cậu cũng bị kéo vào những câu chuyện ly kỳ của thế giới chú thuật. Từ đây cậu cũng gặp được người thầy Gojo Satoru và những người bạn như Megumi, Nobara,... cũng như đối mặt với những chú linh, chú nguyền sư đầy nguy hiểm....",
        image: image_1,
        logo: "",
        year: "2020",
        time: "23ph",
        limit: "16+",
        actor: "Enoki Junya, Uchida Yuma, Seto Asami, Nakamura Yuichi, Suwabe Junichi,Tsuda Kenjiro",
        genre: "Anime hành động, Anime giả tưởng.",
        country: "Nhật Bản",
        video: "https://www.youtube.com/embed/miiLadou1cw",
    },
    {
        id: 2,
        name: "Haikyuu!!",
        desc: "Hinata Shouyou - anh main, sau khi xem xong 1 trận bóng chuyền nọ, đã thần tượng và mơ ước trở thành 'Người khổng lồ tí hon', và gia nhập đội bóng chuyền của trường trung học. Sau khi tìm đủ thành viên, họ đã tham gia giải đấu liên trường, tại đây họ đã chạm trán với 'Vua sân đấu' Kageyama Tobio và bị dập cho tả tơi. Dù thua nhưng Shouyou vẫn quyết tâm lên top và trả đũa Kageyama. Tuy nhiên, lên cấp 3, oan gia ngõ hẹp thế nào, 2 cậu bé lại gặp nhau trong cùng 1 đội. Câu chuyện sẽ tiếp diễn ra sao?",
        image: image_2,
        logo: "",
        year: "2020",
        time: "24ph",
        limit: "10+",
        actor: "Murase Ayumu, Ishikawa Kaito, Hino Satoshi, Irino Miyu, Hayashi Yu, Uchiyama Koki,..",
        genre: "Anime chính kịch, Anime thể thao.",
        country: "Nhật Bản",
        video: "https://www.youtube.com/embed/JOGp2c7-cKc",
    },
    {
        id: 3,
        name: "Howl's Moving Castle",
        desc: "Phim nói về một hành trình phiêu lưu của Sophie Hatter. Cô vốn sinh sống và làm việc yên ổn trong cửa hàng mũ của gia đình tại Ingary - xứ sở kỳ lạ nơi những đôi ủng bảy lý và áo tàng hình được chấp nhận và tôn vinh. Sophie chấp nhận số phận an bày như thế cho đến một ngày nọ, mụ phù thủy xứ Waste xuất hiện biến cô thành bà già xấu xí. Sophie bỏ đi, lên đường tìm kiếm sự giúp đỡ với quyết tâm hóa giải lời nguyền ám lên bản thân. Nào ngờ đâu, cô lại bị cuốn vào hằng sa số những sự kiện liên quan đến Pháp sư Howl - kẻ vốn bị đồn là khoái “ăn tươi nuốt sống” trái tim của những cô gái trẻ.",
        image: image_3,
        logo: "",
        year: "2004",
        time: "1g59p",
        limit: "7+",
        actor: "Baisho Chieko, Kimura Takuya, Miwa Akihiro, Gashuin Tatsuya, Kamiki Ryunosuke,..",
        genre: "Movie",
        country: "Nhật Bản",
        video: "https://www.youtube.com/embed/Ag-CyZ1Gng8",
    },
    {
        id: 4,
        name: "Fairy Tail",
        desc: "Một nhóm bốn pháp sư cùng sát cánh thực hiện các nhiệm vụ trên khắp vương quốc và tình bạn của họ ngày càng trở nên gắn bó, mạnh mẽ hơn hết.",
        image: image_4,
        logo: "",
        year: "2014",
        time: "24ph",
        limit: "16+",
        actor: "Kakihara Teetsuya, Hirano Aya, Kugimiya Rie, Nakamura Yuichi, Ohara Sayaka,....",
        genre: "Anime hành động, Anime giả tưởng",
        country: "Nhật Bản",
        video: "https://www.youtube.com/embed/PNjZK4mInr0",
    },
    {
        id: 5,
        name: "Naruto",
        desc: "Được chỉ dẫn bởi Cữu Vỹ Hồ bị phong ấn trong cơ thể cậu, Naruto đã học cách sử dụng sức mạnh của mình, phấn đấu từng bước để có thể đạt tới ước mơ làm Hokage và cùng với đó là để mọi người công nhận bản thân cậu. Một hành trình mới mở ra, bao vất vả khó khăn ập đến nhưng cậu không từ bỏ. Liệu rằng tương lai của cậu sẽ ra sao ?",
        image: image_5,
        logo: "",
        year: "2017",
        time: "23ph",
        limit: "16+",
        actor: "Takeuchi Junko, Nakamura Chie, Inoue Kazuhiko, Sugiyama Noriaki, Katsuki Masako, Ishida Akira,..",
        genre: "Anime hành động",
        country: "Nhật Bản",
        video: "https://www.youtube.com/embed/QczGoCmX-pI",
    },
    {
        id: 6,
        name: "Spirited Away",
        desc: "",
        image: image_6,
        logo: "",
        year: "2001",
        time: "2g5ph",
        limit: "13+",
        actor: "Hiiragi Rumi, Irino Miyu, Natsuki Mari, Naito Takashi, Sawaguchi Yasuko,...",
        genre: "Movie",
        country: "Nhật Bản",
        video: "https://www.youtube.com/embed/CHCUkXUPkFM",
    },
    {
        id: 7,
        name: "Bungou Stray Dogs - DEAD APPLE",
        desc: "Người mang năng lực trên khắp thế giới đột nhiên tự tử hàng loạt sau khi một màn sương bí ẩn xuất hiện tại hiện trường. Theo yêu cầu của Sakaguchi Ango, Cục Thám tử Vũ trang tiến hành điều tra Shibusawa Tatsuhiko, một kẻ có năng lực với biệt danh 'Nhà Sưu tầm', kẻ tình nghi số một gây nên những vụ án kì lạ trên.",
        image: image_7,
        logo: "",
        year: "2018",
        time: "1h30p",
        limit: "16+",
        actor: "",
        genre: "Movie",
        country: "Nhật Bản",
        video: "https://www.youtube.com/embed/6ySfGSAbNc0",
    },
    {
        id: 8,
        name: "Kimetsu no Yaiba",
        desc: "Tanjiro là con cả trong một gia đình không còn người cha. Một hôm, Tanjiro đi bán than ở một ngôi làng nọ và phải ở lại đó qua đêm vì có tin đồn rằng, về đêm, luôn có một con quỷ lởn vởn ở ngọn núi gần đó. Khi Tanjiro đi về nhà vào ngày hôm sau, bi kịch đang chờ đón cậu.",
        image: image_8,
        logo: "",
        year: "2020",
        time: "24ph",
        limit: "16+",
        actor: "",
        genre: "Anime hành động",
        country: "Nhật Bản",
        video: "https://www.youtube.com/embed/a9tq0aS5Zu8",
    },
    {
        id: 9,
        name: "Chainsaw Man",
        desc: "Tác giả của 'Fire Punch' lần đầu tiên xuất hiện trên Shonen Jump với câu chuyện về một Dark Hero!Cậu thiếu niên Denji sống một cuộc sống nghèo khổ và phải làm việc vất vả để trả nợ. Cậu vừa sống vừa làm Thợ Săn Qủy cùng với Pochita - loài quỷ Chainsaw, nhưng rồi một ngày cậu trở thành mục tiêu của mọt con quỷ tàn bạo...",
        image: image_9,
        logo: "",
        year: "2022",
        time: "24ph",
        limit: "17+",
        actor: "",
        genre: "Anime hành động, Anime giả tưởng",
        country: "Nhật Bản",
        video: "https://www.youtube.com/embed/v4yLeNt-kCU",
    },


]

export default data;